import FooterPage from "@/components/Footer/FooterPage"
import HeaderPage from "@/components/Header/HeaderPage"

export const metadata = {
  title: 'Next.js Demo',
  description: 'Generated by create next app',
}


export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      
      <body>

      <HeaderPage />

        {children}

      <FooterPage />
      </body>
    </html>
  )
}