import FooterPage from "@/components/Footer/FooterPage"
import HeaderPage from "@/components/Header/HeaderPage"
import { Metadata } from "next"



export const metadata: Metadata = {
  title: {
    absolute: "",
    default: "Next js app - krnptl",
    template: "%s | Next.js app - krnptl",
  },
  description: 'Generated by create next app',
}


export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      
      <body>

      <HeaderPage />

      
        {children}
      
      
      <FooterPage />
      </body>
    </html>
  )
}